### ISSUE TITLE
Docker/linux support

### ISSUE THREAD

**Issue by seertenedos** [PlasticSCM/FuseSharp#3]
I would love to see a prebuilt version that would work on linux or even some docker images that could be used to build it and form the base for an app based on it.

How come no precompiled nugets are not available is it because it get tied to the fuse library on the host or something? I would love to be able to develop in VS2019 on windows but have it execute the code in a docker image.  VS2019 on windows is greate for dev but i like to run my apps on linux/docker once they are ready for use.

**Comment by SergioLuis** [comment]
Hi, right now this version only supports macOS, and we don't distribute it in any way - except for source code. Thank you for your interest!
